# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# The pipeline to fetch .Net Nuget packages to the feed
# https://pkgs.dev.azure.com/ms/react-native/_packaging/react-native-public/nuget/v3/index.json
#

trigger: none
pr: none

pool:
  vmImage: windows-latest

variables:
  FEED_URL: "https://pkgs.dev.azure.com/ms/react-native/_packaging/react-native-public/nuget/v3/index.json"
  PACKAGE_ID: "Microsoft.AspNetCore.App.Runtime.linux-x64"
  PACKAGE_VERSION: "9.0.9"

steps:
  - task: NuGetToolInstaller@1
    displayName: "Install NuGet CLI"

  - task: NuGetAuthenticate@1
    displayName: "Authenticate to Azure Artifacts"

  - powershell: |
      $ErrorActionPreference = 'Stop'
      Write-Host "Fetching $env:PACKAGE_ID $env:PACKAGE_VERSION from feed"

      # Build flat container URL and download directly via the feed (avoids install compatibility checks)
      $base = $env:FEED_URL -replace "/index.json$","/"
      $idLower = $env:PACKAGE_ID.ToLowerInvariant()
      $nupkgName = "$idLower.$($env:PACKAGE_VERSION).nupkg"
      $flatUrl = "${base}flat2/$idLower/$($env:PACKAGE_VERSION)/$nupkgName"
      $outPath = Join-Path $env:Agent_TempDirectory $nupkgName

      # Use bearer token (System.AccessToken) instead of basic
      $auth = "Bearer $($env:SYSTEM_ACCESSTOKEN)"

      Write-Host "Downloading from $flatUrl"
      Invoke-WebRequest -Uri $flatUrl -OutFile $outPath -Headers @{ Authorization = $auth }
      Write-Host "Saved to $outPath"
    displayName: "Prefetch package into feed"
    env:
      NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
