# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# The pipeline to fetch .Net Nuget packages to the feed
# https://pkgs.dev.azure.com/ms/react-native/_packaging/react-native-public/nuget/v3/index.json
#

trigger: none
pr: none

pool:
  vmImage: windows-latest

variables:
  FEED_URL: "https://pkgs.dev.azure.com/ms/react-native/_packaging/react-native-public/nuget/v3/index.json"
  PACKAGE_ID: "Microsoft.AspNetCore.App.Runtime.linux-x64"
  PACKAGE_VERSION: "10.0.0"

steps:
  - task: NuGetToolInstaller@1
    displayName: "Install NuGet CLI"

  - task: NuGetAuthenticate@1
    displayName: "Authenticate to Azure Artifacts"

  - powershell: |
      $ErrorActionPreference = 'Stop'
      Write-Host "Fetching $env:PACKAGE_ID $env:PACKAGE_VERSION from feed"
      nuget install $env:PACKAGE_ID `
        -Version $env:PACKAGE_VERSION `
        -Source "$env:FEED_URL" `
        -DirectDownload `
        -NonInteractive `
        -Verbosity detailed
    displayName: "Prefetch package into feed"
    env:
      NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true
