trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)

resources:
  pipelines:
  - pipeline: 'microsoft_node-api-dotnet_ci'
    project: 'ISS'
    source: 'microsoft.node-api-dotnet.ci'
    trigger:
      branches:
        include:
        - main

  repositories:
  - repository: CustomPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/OfficePipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/Office.Official.PipelineTemplate.yml@CustomPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      vmImage: windows-latest
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling-BulkMigrated-Release

    stages:
    - stage: npmjs_com_npm_publish
      displayName: npm npmjs.com feed
      jobs:
      - job: npmjs_com_npm_job
        displayName: Agent job
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          inputs:
          - input: pipelineArtifact
            pipeline: microsoft_node-api-dotnet_ci
            artifactName: 'published-packages'
            targetPath: $(Pipeline.Workspace)\published-packages

        steps:
        - script: dir /S $(Pipeline.Workspace)\published-packages
          displayName: Show directory contents

        - task: 'SFP.release-tasks.custom-build-release-task.EsrpRelease@9'
          displayName: 'ESRP Release to npmjs.com'
          inputs:
            connectedservicename: 'ESRP-JSHost3'
            usemanagedidentity: false
            keyvaultname: 'OGX-JSHost-KV'
            authcertname: 'OGX-JSHost-Auth4'
            signcertname: 'OGX-JSHost-Sign3'
            clientid: '0a35e01f-eadf-420a-a2bf-def002ba898d'
            domaintenantid: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
            contenttype: npm
            folderlocation: $(Pipeline.Workspace)\published-packages
            owners: 'vmorozov@microsoft.com'
            approvers: 'khosany@microsoft.com'
