# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories

name: Test Report
on:
  workflow_run:
    workflows: ['PR Verification'] # runs after 'PR Verification' workflow
    types:
      - completed

permissions:
  checks: write
  pull-requests: write
  statuses: write

jobs:
  report:
    strategy:
      matrix: # This must be kept in sync with the PR build matrix.
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        dotnet-version: [ net472, net8.0, net9.0]
        node-version: [ 18.x, 22.x ]
        configuration: [ Release ]
        exclude:
          # Exclude Node 18.x on .NET < 9, to thin the matrix.
          - dotnet-version: net8.0
            node-version: 18.x
          - dotnet-version: net472
            node-version: 18.x
          # Exclude .NET 4.x on non-Windows OS.
          - os: macos-latest
            dotnet-version: net472
          - os: ubuntu-latest
            dotnet-version: net472

    runs-on: ubuntu-latest

    steps:
    - name: Publish test results
      uses: dorny/test-reporter@v1
      with:
        artifact: test-logs-${{ matrix.os }}-${{matrix.dotnet-version}}-node${{matrix.node-version}}-${{matrix.configuration}}
        name: test results (${{ matrix.os }}, ${{matrix.dotnet-version}}, node${{ matrix.node-version }}, ${{ matrix.configuration }})
        path: test/**/*.trx
        reporter: dotnet-trx
